# Italian Solvency reports Table S.02.01.02; Part 3 Cross-Validation

The purpose of this document is to perform the third stage of the S.02.01.02 transcribing. Cross-validation takes the table and performs a series of internal consistency checks. First on an aggregate level and then for each company in the dataset. The functions return a None if the check is passed or the fields that are compared if the check fails. This allows the user to quickly identify the mistakes in the transcribing. 

The way we operate this notebook is that we first look at the summary of all companies. If the entire array is true (all tests pass for all companies), then the process moves into the final phase. if not, the user looks further down through the notebook. Where a test fails, the relevant fields are displayed. The user than compares the pdf with the values displayed. If any corrections are necessary, the user does them above the test in code. In this way, when the script is ran again, the tests pass.

## Description of the process

The process of extraction is performed in 5 phases:

### Phase 1: Find the reports and identify the relevant tables. 
 1) Identify the new SFCR report and save it into the folder Input.
 2) Identify the pages where the tables of interest are.
 3) Compile the map of the company run in the master_list.csv.

### Phase 2: Run the Extraction code (this script). 
The code performs the following steps (with slight modifications depending on the table format):
 1) Save the page with the table into a separate folder Single_pdf.
 2) Use either a Python package or specialized LLM to create a digital equivalent of the table.
 3) Save the DataFrame into the Output folder.

### Phase 3: Manual check. 
Manually compare the numbers between the final table and the single pdf page. 

### Phase 4: Run the Cross-Validation script. 
Applies a series of tests that check for the internal consistency between the numbers. Flags the potential errors.

### Phase 5: Final modifications to the table and a manual inspection.

### Tolerance

In [24]:
eps = 1.5

#### Necessary packages

In [25]:
import pandas as pd
import numpy as np

### Functions

In [26]:
def check_02_01_02_1(data:pd.DataFrame, eps:float, col:str):
    """
    R0100 = R0110 + R0120
    
    """

    lhs = data.loc["R0100",col]
    rhs = data.loc["R0110",col] + data.loc["R0120",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        return False, pd.DataFrame(data = [data.loc["R0110",col], data.loc["R0120",col], data.loc["R0100",col]], index=["R0110", "R0120","R0100"], columns = ["TEST_1"]), diff

In [27]:
def check_02_01_02_2(data:pd.DataFrame, eps:float, col:str):
    """
    R0130 = R0140 + R0150 + R0160 + R0170
    
    """

    lhs = data.loc["R0130",col]
    rhs = data.loc["R0140",col] + data.loc["R0150",col]+ data.loc["R0160",col]+ data.loc["R0170",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0140",col], data.loc["R0150",col], data.loc["R0160",col], data.loc["R0170",col], data.loc["R0130",col]]
        dagnostics_index = ["R0140", "R0150", "R0160", "R0170", "R0130"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_2"]), diff

In [28]:
def check_02_01_02_3(data:pd.DataFrame, eps:float, col:str):
    """
    R0070 = R0080 + R0090 + R0100 + R0130 + R0180 + R0190 + R0200 + R0210
    
    """

    lhs = data.loc["R0070",col]
    rhs = data.loc["R0080",col] + data.loc["R0090",col]+ data.loc["R0100",col]+ data.loc["R0130",col] + data.loc["R0180",col]+ data.loc["R0190",col]+ data.loc["R0200",col]+ data.loc["R0210",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0080",col], data.loc["R0090",col], data.loc["R0100",col], data.loc["R0130",col],
                      data.loc["R0180",col], data.loc["R0190",col], data.loc["R0200",col], data.loc["R0210",col], data.loc["R0070",col]]
            
        dagnostics_index = ["R0080", "R0090", "R0100", "R0130", "R0180", "R0190", "R0200","R0210", "R0070"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_3"]), diff

In [29]:
def check_02_01_02_4(data:pd.DataFrame, eps:float, col:str):
    """
    R0230 = R0240 + R0250 + R0260
    """

    lhs = data.loc["R0230",col]
    rhs = data.loc["R0240",col] + data.loc["R0250",col]+ data.loc["R0260",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0240",col], data.loc["R0250",col], data.loc["R0260",col], data.loc["R0230",col]]
        dagnostics_index = ["R0240", "R0250", "R0260", "R0230"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_4"]), diff

In [30]:
def check_02_01_02_5(data:pd.DataFrame, eps:float, col:str):
    """
    R0270 = R0280 + R0310 + R0340
    """

    lhs = data.loc["R0270",col]
    rhs = data.loc["R0280",col] + data.loc["R0310",col]+ data.loc["R0340",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0280",col], data.loc["R0310",col], data.loc["R0340",col], data.loc["R0270",col]]
        dagnostics_index = ["R0280", "R0310", "R0340", "R0270"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_5"]), diff

In [31]:
def check_02_01_02_6(data:pd.DataFrame, eps:float, col:str):
    """
    R0310 = R0320 + R0330
    
    """

    lhs = data.loc["R0310",col]
    rhs = data.loc["R0320",col] + data.loc["R0330",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0320",col], data.loc["R0330",col], data.loc["R0310",col]]
        dagnostics_index = ["R0320", "R0330", "R0310"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_6"]), diff

In [32]:
def check_02_01_02_7(data:pd.DataFrame, eps:float, col:str):
    """
    R0280 = R0290 + R0300
    
    """

    lhs = data.loc["R0280",col]
    rhs = data.loc["R0290",col] + data.loc["R0300",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0290",col], data.loc["R0300",col], data.loc["R0280",col]]
        dagnostics_index = ["R0290", "R0300", "R0280"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_7"]), diff

In [33]:
def check_02_01_02_8(data:pd.DataFrame, eps:float, col:str): # TO INPLEMENT ONCE ALL FIELDS ARE COVERED
    """
    R0500 = R0030 + R0040 + R0050 + R0060 + R0070 + R0220 + R0230 + 
            R0270 + R0350 + R0360 + R0370 + R0380 + R0390 + R0400 + R0410 + R0420

    """

    lhs = data.loc["R0500",col]
    rhs = data.loc["R0030",col] + data.loc["R0040",col] + data.loc["R0050",col] + data.loc["R0060",col] + data.loc["R0070",col] + data.loc["R0220",col] + data.loc["R0230",col] + data.loc["R0270",col] + data.loc["R0350",col] + data.loc["R0360",col]+ data.loc["R0370",col]+ data.loc["R0380",col]+ data.loc["R0390",col]+ data.loc["R0400",col]+ data.loc["R0410",col]+ data.loc["R0420",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0030",col], data.loc["R0040",col], data.loc["R0050",col], data.loc["R0060",col], data.loc["R0070",col], data.loc["R0220",col], data.loc["R0230",col], data.loc["R0270",col], data.loc["R0350",col], data.loc["R0360",col], data.loc["R0370",col], data.loc["R0380",col], data.loc["R0390",col], data.loc["R0400",col], data.loc["R0410",col], data.loc["R0420",col], data.loc["R0500",col]]
        dagnostics_index = ["R0030", "R0040", "R0050", "R0060", "R0070", "R0220", "R0230", "R0270", "R0350", "R0360", "R0370", "R0380", "R0390", "R0400", "R0410", "R0420", "R0500"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_8"]), diff

In [34]:
def check_02_01_02_9(data:pd.DataFrame, eps:float, col:str):
    """
    R0510 = R0520 + R0560
    
    """

    lhs = data.loc["R0510",col]
    rhs = data.loc["R0520",col] + data.loc["R0560",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0520",col], data.loc["R0560",col], data.loc["R0510",col]]
        dagnostics_index = ["R0520", "R0560", "R0510"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_9"]), diff

In [35]:
def check_02_01_02_10(data:pd.DataFrame, eps:float, col:str):
    """
    R0520 = R0530 + R0540 + R0550
    
    """

    lhs = data.loc["R0520",col]
    rhs = data.loc["R0530",col] + data.loc["R0540",col]+ data.loc["R0550",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0530",col], data.loc["R0540",col], data.loc["R0550",col], data.loc["R0520",col]]
        dagnostics_index = ["R0530", "R0540", "R0550", "R0520"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_10"]), diff

In [36]:
def check_02_01_02_11(data:pd.DataFrame, eps:float, col:str):
    """
    R0560 = R0570 + R0580 + R0590
    
    """

    lhs = data.loc["R0560",col]
    rhs = data.loc["R0570",col] + data.loc["R0580",col]+ data.loc["R0590",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0570",col], data.loc["R0580",col], data.loc["R0590",col], data.loc["R0560",col]]
        dagnostics_index = ["R0570", "R0580", "R0590", "R0560"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_11"]), diff

In [37]:
def check_02_01_02_12(data:pd.DataFrame, eps:float, col:str):
    """
    R0600 = R0610 + R0650
    
    """

    lhs = data.loc["R0600",col]
    rhs = data.loc["R0610",col] + data.loc["R0650",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0610",col], data.loc["R0650",col], data.loc["R0600",col]]
        dagnostics_index = ["R0610", "R0650", "R0600"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_12"]), diff

In [38]:
def check_02_01_02_13(data:pd.DataFrame, eps:float, col:str):
    """
    R0610 = R0620 + R0630 + R0640
    
    """

    lhs = data.loc["R0610",col]
    rhs = data.loc["R0620",col] + data.loc["R0630",col]+ data.loc["R0640",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0620",col], data.loc["R0630",col], data.loc["R0640",col], data.loc["R0610",col]]
        dagnostics_index = ["R0620", "R0630", "R0640", "R0610"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_13"]), diff

In [39]:
def check_02_01_02_14(data:pd.DataFrame, eps:float, col:str):
    """
    R0650 = R0660 + R0670 + R0680
    
    """

    lhs = data.loc["R0650",col]
    rhs = data.loc["R0660",col] + data.loc["R0670",col]+ data.loc["R0680",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0660",col], data.loc["R0670",col], data.loc["R0680",col], data.loc["R0650",col]]
        dagnostics_index = ["R0660", "R0670", "R0680", "R0650"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_14"]), diff

In [40]:
def check_02_01_02_15(data:pd.DataFrame, eps:float, col:str):
    """
    R0690 = R0700 + R0710 + R0720
    
    """

    lhs = data.loc["R0690",col]
    rhs = data.loc["R0700",col] + data.loc["R0710",col]+ data.loc["R0720",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0700",col], data.loc["R0710",col], data.loc["R0720",col], data.loc["R0690",col]]
        dagnostics_index = ["R0700", "R0710", "R0720", "R0690"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_15"]), diff

In [41]:
def check_02_01_02_16(data:pd.DataFrame, eps:float, col:str):
    """
    R0850 = R0860 + R0870
    
    """

    lhs = data.loc["R0850",col]
    rhs = data.loc["R0860",col] + data.loc["R0870",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0860",col], data.loc["R0870",col], data.loc["R0850",col]]
        dagnostics_index = ["R0860", "R0870", "R0850"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_12"]), diff

In [42]:
def check_02_01_02_17(data:pd.DataFrame, eps:float, col:str):
    """
    R1000 = R0500 - R0900
    
    """

    lhs = data.loc["R1000",col]
    rhs = data.loc["R0500",col] - data.loc["R0900",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0500",col], data.loc["R0900",col], data.loc["R1000",col]]
        dagnostics_index = ["R0500", "R0900", "R1000"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_17"]), diff

In [43]:
def run_check_diagnostics(table, function, col_name, eps):
    results = pd.DataFrame(data=[], columns=["COMPANY_NAME",col_name])
    for col in table.columns:
        res, diag, observed_tol = function(table, eps=eps, col=col)
        result_tmp = pd.DataFrame(data=[[col, res]], columns = ["COMPANY_NAME",col_name])
        results = pd.concat([results, result_tmp])
        results[results == True] =""
        
    return results

## Dirty table

In [44]:
dirty_table_ita =  pd.read_csv("Final_output/S020102_partial_final.csv", header=0, index_col=0, decimal = ".", thousands=",")

In [45]:
dirty_table_ita

,AXA,GENERALI ITALIA,HDI,ZURICH_LIFE,CREDIT_AGRICOLE,CREDEM_VITA,CARDIF,HELVETIA_VITA,BMP VITA,UNICREDIT VITA,CNP_VITA,ALLIANZ_UNICREDIT,ATHORA
R0010,0.000000e+00,0,0,0,0,0,0.00,0,0,0,0,0,0
R0030,0.000000e+00,0,0,0,0,0,0.00,0,0,0,0,0,0
R0040,0.000000e+00,83675,9916,0,0,639,0.00,1001,6301,0,0,0,252864
R0050,0.000000e+00,0,0,0,0,0,0.00,0,0,0,0,0,0
R0060,7.498775e+06,453560,41752,3423,46214,755,39.00,43447,3113,40749,2957,0,2154
...,...,...,...,...,...,...,...,...,...,...,...,...,...
R0870,1.291100e+08,248817,167419,0,682977,0,313197.17,73388,8000,0,453926,90009,81858
R0880,1.673012e+07,1011107,33473,67566,138305,2639,0.00,9544,2641,42,86158,76512,8945
R0890,0.000000e+00,0,0,0,0,0,0.00,0,0,0,0,0,0
R0900,1.735640e+10,96166794,5943050,10744729,25956724,10441151,23625315.34,3901435,7115769,15976536,24378745,30016503,5644301
R1000,1.538968e+09,21267958,837845,775308,1378477,828242,1352256.97,299693,1388915,1184228,1914325,1472117,332863

## Overview of quality

In [46]:
results_1 = run_check_diagnostics(dirty_table_ita, check_02_01_02_1, "TEST_1", eps)
results_1 = results_1.set_index("COMPANY_NAME")

In [47]:
results_2 = run_check_diagnostics(dirty_table_ita, check_02_01_02_2, "TEST_2", eps)
results_2 = results_2.set_index("COMPANY_NAME")

In [48]:
results_3 = run_check_diagnostics(dirty_table_ita, check_02_01_02_3, "TEST_3", eps)
results_3 = results_3.set_index("COMPANY_NAME")

In [49]:
results_4 = run_check_diagnostics(dirty_table_ita, check_02_01_02_4, "TEST_4", eps)
results_4 = results_4.set_index("COMPANY_NAME")

In [50]:
results_5 = run_check_diagnostics(dirty_table_ita, check_02_01_02_5, "TEST_5", eps)
results_5 = results_5.set_index("COMPANY_NAME")

In [51]:
results_6 = run_check_diagnostics(dirty_table_ita, check_02_01_02_6, "TEST_6", eps)
results_6 = results_6.set_index("COMPANY_NAME")

In [52]:
results_7 = run_check_diagnostics(dirty_table_ita, check_02_01_02_7, "TEST_7", eps)
results_7 = results_7.set_index("COMPANY_NAME")

In [53]:
results_8 = run_check_diagnostics(dirty_table_ita, check_02_01_02_8, "TEST_8", eps)
results_8 = results_8.set_index("COMPANY_NAME")

In [54]:
results_9 = run_check_diagnostics(dirty_table_ita, check_02_01_02_9, "TEST_9", eps)
results_9 = results_9.set_index("COMPANY_NAME")

In [55]:
results_10 = run_check_diagnostics(dirty_table_ita, check_02_01_02_10, "TEST_10", eps)
results_10 = results_10.set_index("COMPANY_NAME")

In [56]:
results_11 = run_check_diagnostics(dirty_table_ita, check_02_01_02_11, "TEST_11", eps)
results_11 = results_11.set_index("COMPANY_NAME")

In [57]:
results_12 = run_check_diagnostics(dirty_table_ita, check_02_01_02_12, "TEST_12", eps)
results_12 = results_12.set_index("COMPANY_NAME")

In [58]:
results_13 = run_check_diagnostics(dirty_table_ita, check_02_01_02_13, "TEST_13", eps)
results_13 = results_13.set_index("COMPANY_NAME")

In [59]:
results_14 = run_check_diagnostics(dirty_table_ita, check_02_01_02_14, "TEST_14", eps)
results_14 = results_14.set_index("COMPANY_NAME")

In [60]:
results_15 = run_check_diagnostics(dirty_table_ita, check_02_01_02_15, "TEST_15", eps)
results_15 = results_15.set_index("COMPANY_NAME")

In [61]:
results_16 = run_check_diagnostics(dirty_table_ita, check_02_01_02_16, "TEST_16", eps)
results_16 = results_16.set_index("COMPANY_NAME")

In [62]:
results_17 = run_check_diagnostics(dirty_table_ita, check_02_01_02_17, "TEST_17", eps)
results_17 = results_17.set_index("COMPANY_NAME")

In [63]:
overall_summary = pd.concat([results_1,results_2,results_3,results_4,results_5,results_6,results_7,results_8,results_9,results_10,results_11,
                             results_12,results_13,results_14,results_15,results_16,results_17], axis=1)

In [64]:
display(overall_summary)

,TEST_1,TEST_2,TEST_3,TEST_4,TEST_5,TEST_6,TEST_7,TEST_8,TEST_9,TEST_10,TEST_11,TEST_12,TEST_13,TEST_14,TEST_15,TEST_16,TEST_17
COMPANY_NAME,,,,,,,,,,,,,,,,,
AXA,,,,,,,,,,,,,,,,,
GENERALI ITALIA,,,,,,,,,,,,,,,,,
HDI,,,,,,,,,,,,,,,,,
ZURICH_LIFE,,,,,,,,,,,,,,,,,
CREDIT_AGRICOLE,,,,,,,,,,,,,,,,,
CREDEM_VITA,,,,,,,,,,,,,,,,,
CARDIF,,,,,,,,,,,,,,,,,
HELVETIA_VITA,,,,,,,,,,,,,,,,,
BMP VITA,,,,,,,,,,,,,,,,,
UNICREDIT VITA,,,,,,,,,,,,,,,,,
CNP_VITA,,,,,,,,,,,,,,,,,
ALLIANZ_UNICREDIT,,,,,,,,,,,,,,,,,
ATHORA,,,,,,,,,,,,,,,,,

## Manual overwrites

## Credemvita S.p.A.

In [65]:
unique_code = "CREDEM_VITA"

In [66]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [67]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [68]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [69]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [70]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [71]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [72]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [73]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [74]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [75]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [76]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [77]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [78]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [79]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [80]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [81]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [82]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## AXA MPS Assicurazioni Vita

In [83]:
unique_code = "AXA"

In [84]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [85]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [86]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [87]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [88]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [89]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [90]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [91]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [92]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [93]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [94]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [95]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [96]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [97]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [98]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [99]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [100]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## CRÈDIT AGRICOLE VITA

In [101]:
unique_code = "CREDIT_AGRICOLE"

In [102]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [103]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [104]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [105]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [106]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [107]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [108]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [109]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [110]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [111]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [112]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [113]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [114]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [115]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [116]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [117]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [118]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## Società Reale Mutua di Assicurazioni

In [119]:
unique_code = "REALE_MUTUA"

In [120]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

KeyError: 'REALE_MUTUA'

In [ ]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## Cardif Vita S.p.A.

In [ ]:
unique_code = "CARDIF"

In [ ]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## MEDIOLANUM VITA S.p.A.

In [ ]:
unique_code = "MEDIOLANUM"

In [ ]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## Generali Italia S.p.A.

In [ ]:
unique_code = "GENERALI ITALIA"

In [ ]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
#dirty_table_ita.loc["R0100", unique_code] = 4034485

In [ ]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## Banco BPM Vita S.p.A.

In [ ]:
unique_code = "BMP VITA"

In [ ]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
dirty_table_ita.loc["R0860",unique_code] = 0

In [ ]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## HDI ASSICURAZIONI S.p.A.

In [ ]:
unique_code = "HDI"

In [ ]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## Gruppo Assicurativo Poste Vita

In [ ]:
unique_code = "POSTE_VITA"

In [ ]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## FIDEURAM VITA S.P.A.

In [ ]:
unique_code = "INTESA_VITA"

In [ ]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## CNP Vita Assicura S.p.A.

In [ ]:
unique_code = "CNP_VITA"

In [ ]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

# ITAS VITA

In [ ]:
unique_code = "ITAS_VITA"

In [ ]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## Helvetia Vita S.p.A.

In [ ]:
unique_code = "HELVETIA_VITA"

In [ ]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## Vittoria Assicurazioni S.p.A.

In [ ]:
unique_code = "VITTORIA"

In [ ]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## GROUPAMA ASSICURAZIONI S.P.A.

In [ ]:
unique_code = "GROUPAMA"

In [ ]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## UniCredit Allianz Vita S.p.A.

In [ ]:
unique_code = "ALLIANZ_UNICREDIT"

In [ ]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## Zurich Investments Life S.p.A.

In [ ]:
unique_code = "ZURICH_LIFE"

In [ ]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## UNICREDIT VITA

In [ ]:
unique_code = "UNICREDIT VITA"

In [ ]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [ ]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## ATHORA

In [121]:
unique_code = "ATHORA"

In [122]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [123]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [124]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [125]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [126]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [127]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [128]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [129]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [130]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [131]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [132]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [133]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [134]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [135]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [136]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [137]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [138]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## Master table after cross checks

In [139]:
#dirty_table_ita.to_csv("Cleaner_Combined/Table_ita_S02.csv")