# Italian Solvency reports Table S.02.01.02; Part 3 Cross-Validation

The purpose of this document is to perform the third stage of the S.02.01.02 transcribing. Cross-validation takes the table and performs a series of internal consistency checks. First on an aggregate level and then for each company in the dataset. The functions return a None if the check is passed or the fields that are compared if the check fails. This allows the user to quickly identify the mistakes in the transcribing. 

The way we operate this notebook is that we first look at the summary of all companies. If the entire array is true (all tests pass for all companies), then the process moves into the final phase. if not, the user looks further down through the notebook. Where a test fails, the relevant fields are displayed. The user than compares the pdf with the values displayed. If any corrections are necessary, the user does them above the test in code. In this way, when the script is ran again, the tests pass.

## Description of the process

The process of extraction is performed in 5 phases:

### Phase 1: Find the reports and identify the relevant tables. 
 1) Identify the new SFCR report and save it into the folder Input.
 2) Identify the pages where the tables of interest are.
 3) Compile the map of the company run in the master_list.csv.

### Phase 2: Run the Extraction script (this script). 
The script performs the following steps (with slight modifications depending on the table format):
 1) Save the page with the table into a separate folder Single_pdf.
 2) Use either a Python package or specialized LLM to create a digital equivalent of the table.
 3) Fix the systemic errors that prevent the table from being saved as DataFrame.
 4) Save the DataFrame into the Output folder.

### Phase 3: Run the Processing script. 
The script applies fixes to the DataFrame to make the numbers closer to the reported numbers. It joins all the tables into a single dataset. 

### Phase 4: Run the Cross-Validation script. 
Applies a series of tests that check for the internal consistency between the numbers. Flags the potential errors.

### Phase 5: Final modifications to the table and a manual inspection.

### Tolerance

In [8498]:
eps = 1.5

#### Necessary packages

In [8499]:
import pandas as pd
import numpy as np

### Functions

In [8500]:
def check_02_01_02_1(data:pd.DataFrame, eps:float, col:str):
    """
    R0100 = R0110 + R0120
    
    """

    lhs = data.loc["R0100",col]
    rhs = data.loc["R0110",col] + data.loc["R0120",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        return False, pd.DataFrame(data = [data.loc["R0110",col], data.loc["R0120",col], data.loc["R0100",col]], index=["R0110", "R0120","R0100"], columns = ["TEST_1"]), diff

In [8501]:
def check_02_01_02_2(data:pd.DataFrame, eps:float, col:str):
    """
    R0130 = R0140 + R0150 + R0160 + R0170
    
    """

    lhs = data.loc["R0130",col]
    rhs = data.loc["R0140",col] + data.loc["R0150",col]+ data.loc["R0160",col]+ data.loc["R0170",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0140",col], data.loc["R0150",col], data.loc["R0160",col], data.loc["R0170",col], data.loc["R0130",col]]
        dagnostics_index = ["R0140", "R0150", "R0160", "R0170", "R0130"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_2"]), diff

In [8502]:
def check_02_01_02_3(data:pd.DataFrame, eps:float, col:str):
    """
    R0070 = R0080 + R0090 + R0100 + R0130 + R0180 + R0190 + R0200 + R0210
    
    """

    lhs = data.loc["R0070",col]
    rhs = data.loc["R0080",col] + data.loc["R0090",col]+ data.loc["R0100",col]+ data.loc["R0130",col] + data.loc["R0180",col]+ data.loc["R0190",col]+ data.loc["R0200",col]+ data.loc["R0210",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0080",col], data.loc["R0090",col], data.loc["R0100",col], data.loc["R0130",col],
                      data.loc["R0180",col], data.loc["R0190",col], data.loc["R0200",col], data.loc["R0210",col], data.loc["R0070",col]]
            
        dagnostics_index = ["R0080", "R0090", "R0100", "R0130", "R0180", "R0190", "R0200","R0210", "R0070"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_3"]), diff

In [8503]:
def check_02_01_02_4(data:pd.DataFrame, eps:float, col:str):
    """
    R0230 = R0240 + R0250 + R0260
    """

    lhs = data.loc["R0230",col]
    rhs = data.loc["R0240",col] + data.loc["R0250",col]+ data.loc["R0260",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0240",col], data.loc["R0250",col], data.loc["R0260",col], data.loc["R0230",col]]
        dagnostics_index = ["R0240", "R0250", "R0260", "R0230"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_4"]), diff

In [8504]:
def check_02_01_02_5(data:pd.DataFrame, eps:float, col:str):
    """
    R0270 = R0280 + R0310 + R0340
    """

    lhs = data.loc["R0270",col]
    rhs = data.loc["R0280",col] + data.loc["R0310",col]+ data.loc["R0340",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0280",col], data.loc["R0310",col], data.loc["R0340",col], data.loc["R0270",col]]
        dagnostics_index = ["R0280", "R0310", "R0340", "R0270"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_5"]), diff

In [8505]:
def check_02_01_02_6(data:pd.DataFrame, eps:float, col:str):
    """
    R0310 = R0320 + R0330
    
    """

    lhs = data.loc["R0310",col]
    rhs = data.loc["R0320",col] + data.loc["R0330",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0320",col], data.loc["R0330",col], data.loc["R0310",col]]
        dagnostics_index = ["R0320", "R0330", "R0310"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_6"]), diff

In [8506]:
def check_02_01_02_7(data:pd.DataFrame, eps:float, col:str):
    """
    R0280 = R0290 + R0300
    
    """

    lhs = data.loc["R0280",col]
    rhs = data.loc["R0290",col] + data.loc["R0300",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0290",col], data.loc["R0300",col], data.loc["R0280",col]]
        dagnostics_index = ["R0290", "R0300", "R0280"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_7"]), diff

In [8507]:
def check_02_01_02_8(data:pd.DataFrame, eps:float, col:str): # TO INPLEMENT ONCE ALL FIELDS ARE COVERED
    """
    R0500 = R0030 + R0040 + R0050 + R0060 + R0070 + R0220 + R0230 + 
            R0270 + R0350 + R0360 + R0370 + R0380 + R0390 + R0400 + R0410 + R0420

    To Do
    """

    lhs = data.loc["R0500",col]
    rhs = data.loc["R0030",col] + data.loc["R0040",col] + data.loc["R0050",col] + data.loc["R0060",col] + data.loc["R0070",col] + data.loc["R0220",col] + data.loc["R0230",col] + data.loc["R0270",col] + data.loc["R0350",col] + data.loc["R0360",col]+ data.loc["R0370",col]+ data.loc["R0380",col]+ data.loc["R0390",col]+ data.loc["R0400",col]+ data.loc["R0410",col]+ data.loc["R0420",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0030",col], data.loc["R0040",col], data.loc["R0050",col], data.loc["R0060",col], data.loc["R0070",col], data.loc["R0220",col], data.loc["R0230",col], data.loc["R0270",col], data.loc["R0350",col], data.loc["R0360",col], data.loc["R0370",col], data.loc["R0380",col], data.loc["R0390",col], data.loc["R0400",col], data.loc["R0410",col], data.loc["R0420",col], data.loc["R0500",col]]
        dagnostics_index = ["R0030", "R0040", "R0050", "R0060", "R0070", "R0220", "R0230", "R0270", "R0350", "R0360", "R0370", "R0380", "R0390", "R0400", "R0410", "R0420", "R0500"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_8"]), diff

In [8508]:
def check_02_01_02_9(data:pd.DataFrame, eps:float, col:str):
    """
    R0510 = R0520 + R0560
    
    """

    lhs = data.loc["R0510",col]
    rhs = data.loc["R0520",col] + data.loc["R0560",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0520",col], data.loc["R0560",col], data.loc["R0510",col]]
        dagnostics_index = ["R0520", "R0560", "R0510"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_9"]), diff

In [8509]:
def check_02_01_02_10(data:pd.DataFrame, eps:float, col:str):
    """
    R0520 = R0530 + R0540 + R0550
    
    """

    lhs = data.loc["R0520",col]
    rhs = data.loc["R0530",col] + data.loc["R0540",col]+ data.loc["R0550",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0530",col], data.loc["R0540",col], data.loc["R0550",col], data.loc["R0520",col]]
        dagnostics_index = ["R0530", "R0540", "R0550", "R0520"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_10"]), diff

In [8510]:
def check_02_01_02_11(data:pd.DataFrame, eps:float, col:str):
    """
    R0560 = R0570 + R0580 + R0590
    
    """

    lhs = data.loc["R0560",col]
    rhs = data.loc["R0570",col] + data.loc["R0580",col]+ data.loc["R0590",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0570",col], data.loc["R0580",col], data.loc["R0590",col], data.loc["R0560",col]]
        dagnostics_index = ["R0570", "R0580", "R0590", "R0560"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_11"]), diff

In [8511]:
def check_02_01_02_12(data:pd.DataFrame, eps:float, col:str):
    """
    R0600 = R0610 + R0650
    
    """

    lhs = data.loc["R0600",col]
    rhs = data.loc["R0610",col] + data.loc["R0650",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0610",col], data.loc["R0650",col], data.loc["R0600",col]]
        dagnostics_index = ["R0610", "R0650", "R0600"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_12"]), diff

In [8512]:
def check_02_01_02_13(data:pd.DataFrame, eps:float, col:str):
    """
    R0610 = R0620 + R0630 + R0640
    
    """

    lhs = data.loc["R0610",col]
    rhs = data.loc["R0620",col] + data.loc["R0630",col]+ data.loc["R0640",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0620",col], data.loc["R0630",col], data.loc["R0640",col], data.loc["R0610",col]]
        dagnostics_index = ["R0620", "R0630", "R0640", "R0610"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_13"]), diff

In [8513]:
def check_02_01_02_14(data:pd.DataFrame, eps:float, col:str):
    """
    R0650 = R0660 + R0670 + R0680
    
    """

    lhs = data.loc["R0650",col]
    rhs = data.loc["R0660",col] + data.loc["R0670",col]+ data.loc["R0680",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0660",col], data.loc["R0670",col], data.loc["R0680",col], data.loc["R0650",col]]
        dagnostics_index = ["R0660", "R0670", "R0680", "R0650"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_14"]), diff

In [8514]:
def check_02_01_02_15(data:pd.DataFrame, eps:float, col:str):
    """
    R0690 = R0700 + R0710 + R0720
    
    """

    lhs = data.loc["R0690",col]
    rhs = data.loc["R0700",col] + data.loc["R0710",col]+ data.loc["R0720",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0700",col], data.loc["R0710",col], data.loc["R0720",col], data.loc["R0690",col]]
        dagnostics_index = ["R0700", "R0710", "R0720", "R0690"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_15"]), diff

In [8515]:
def check_02_01_02_16(data:pd.DataFrame, eps:float, col:str):
    """
    R0850 = R0860 + R0870
    
    """

    lhs = data.loc["R0850",col]
    rhs = data.loc["R0860",col] + data.loc["R0870",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0860",col], data.loc["R0870",col], data.loc["R0850",col]]
        dagnostics_index = ["R0860", "R0870", "R0850"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_12"]), diff

In [8516]:
def check_02_01_02_17(data:pd.DataFrame, eps:float, col:str):
    """
    R1000 = R0500 - R0900
    
    """

    lhs = data.loc["R1000",col]
    rhs = data.loc["R0500",col] - data.loc["R0900",col]
    diff = abs(lhs-rhs)
    if diff< eps:
        return True, None, diff
    else:
        diagnostics = [data.loc["R0500",col], data.loc["R0900",col], data.loc["R1000",col]]
        dagnostics_index = ["R0500", "R0900", "R1000"]
        return False, pd.DataFrame(data = diagnostics, index=dagnostics_index, columns = ["TEST_17"]), diff

In [8517]:
def run_check_diagnostics(table, function, col_name, eps):
    results = pd.DataFrame(data=[], columns=["COMPANY_NAME",col_name])
    for col in table.columns:
        res, diag, observed_tol = function(table, eps=eps, col=col)
        result_tmp = pd.DataFrame(data=[[col, res]], columns = ["COMPANY_NAME",col_name])
        results = pd.concat([results, result_tmp])
        results[results == True] =""
        
    return results

## Dirty table

In [8518]:
dirty_table_ita =  pd.read_csv("Dirty_Combined/Table_ita_S02.csv", header=0, index_col=0)

In [8519]:
dirty_table_ita = dirty_table_ita.loc[dirty_table_ita.index.notna()]

In [8520]:
dirty_table_ita.drop(index=["CODE"],inplace=True)

In [8521]:
dirty_table_ita.drop(columns=["MASTER"],inplace=True)

In [8522]:
dirty_table_ita = dirty_table_ita.astype(float).fillna(0)

## Overview of quality

In [8523]:
results_1 = run_check_diagnostics(dirty_table_ita, check_02_01_02_1, "TEST_1", eps)
results_1 = results_1.set_index("COMPANY_NAME")

In [8524]:
results_2 = run_check_diagnostics(dirty_table_ita, check_02_01_02_2, "TEST_2", eps)
results_2 = results_2.set_index("COMPANY_NAME")

In [8525]:
results_3 = run_check_diagnostics(dirty_table_ita, check_02_01_02_3, "TEST_3", eps)
results_3 = results_3.set_index("COMPANY_NAME")

In [8526]:
results_4 = run_check_diagnostics(dirty_table_ita, check_02_01_02_4, "TEST_4", eps)
results_4 = results_4.set_index("COMPANY_NAME")

In [8527]:
results_5 = run_check_diagnostics(dirty_table_ita, check_02_01_02_5, "TEST_5", eps)
results_5 = results_5.set_index("COMPANY_NAME")

In [8528]:
results_6 = run_check_diagnostics(dirty_table_ita, check_02_01_02_6, "TEST_6", eps)
results_6 = results_6.set_index("COMPANY_NAME")

In [8529]:
results_7 = run_check_diagnostics(dirty_table_ita, check_02_01_02_7, "TEST_7", eps)
results_7 = results_7.set_index("COMPANY_NAME")

In [8530]:
results_8 = run_check_diagnostics(dirty_table_ita, check_02_01_02_8, "TEST_8", eps)
results_8 = results_8.set_index("COMPANY_NAME")

In [8531]:
results_9 = run_check_diagnostics(dirty_table_ita, check_02_01_02_9, "TEST_9", eps)
results_9 = results_9.set_index("COMPANY_NAME")

In [8532]:
results_10 = run_check_diagnostics(dirty_table_ita, check_02_01_02_10, "TEST_10", eps)
results_10 = results_10.set_index("COMPANY_NAME")

In [8533]:
results_11 = run_check_diagnostics(dirty_table_ita, check_02_01_02_11, "TEST_11", eps)
results_11 = results_11.set_index("COMPANY_NAME")

In [8534]:
results_12 = run_check_diagnostics(dirty_table_ita, check_02_01_02_12, "TEST_12", eps)
results_12 = results_12.set_index("COMPANY_NAME")

In [8535]:
results_13 = run_check_diagnostics(dirty_table_ita, check_02_01_02_13, "TEST_13", eps)
results_13 = results_13.set_index("COMPANY_NAME")

In [8536]:
results_14 = run_check_diagnostics(dirty_table_ita, check_02_01_02_14, "TEST_14", eps)
results_14 = results_14.set_index("COMPANY_NAME")

In [8537]:
results_15 = run_check_diagnostics(dirty_table_ita, check_02_01_02_15, "TEST_15", eps)
results_15 = results_15.set_index("COMPANY_NAME")

In [8538]:
results_16 = run_check_diagnostics(dirty_table_ita, check_02_01_02_16, "TEST_16", eps)
results_16 = results_16.set_index("COMPANY_NAME")

In [8539]:
results_17 = run_check_diagnostics(dirty_table_ita, check_02_01_02_17, "TEST_17", eps)
results_17 = results_17.set_index("COMPANY_NAME")

In [8540]:
overall_summary = pd.concat([results_1,results_2,results_3,results_4,results_5,results_6,results_7,results_8,results_9,results_10,results_11,
                             results_12,results_13,results_14,results_15,results_16,results_17], axis=1)

In [8541]:
display(overall_summary)

,TEST_1,TEST_2,TEST_3,TEST_4,TEST_5,TEST_6,TEST_7,TEST_8,TEST_9,TEST_10,TEST_11,TEST_12,TEST_13,TEST_14,TEST_15,TEST_16,TEST_17
COMPANY_NAME,,,,,,,,,,,,,,,,,
CREDEM_VITA,,,,,,,,False,,,,,,,,,
AXA,,,,,,,,,,,,,,,,,
CREDIT_AGRICOLE,,,,,,,,,,,,,,,,,
REALE_MUTUA,,,,,,,,,,,,,,,,,
CARDIF,,,,,,,,,,,,,,,,,
MEDIOLANUM,,,,,False,,,,,,,,False,,,,
GENERALI_ITALIA,False,,False,,False,,,False,,,,,,,,,
BMP_VITA,,,,,,,,,False,,False,,,,,False,
HDI,,False,False,,,,,,,,,,,,,,
POSTE_VITA,,,,,,,,False,False,False,False,False,,,,,
INTESA_VITA,,,,,,,,,,,,,,,,,
CNP_VITA,,,,,,,,False,,,,,,,,,False
ITAS_VITA,,,,,,,,,,,,,,,,,
HELVATIA_VITA,,,,,,,,,,,,,,,,,
VITTORIA,,,,,,,,,,,,,,,,,
GROUPAMA,,,False,,False,False,False,False,,False,,False,,False,,,False
ALLIANZ_UNICREDIT,,,,,,,,,,,,,,,,,
ZURICH_LIFE,,,,,,,,,,,,,,,,,False

## Manual overwrites

## Credemvita S.p.A.

In [8542]:
unique_code = "CREDEM_VITA"

In [ ]:
dirty_table_ita.loc["R0410",unique_code] = 82134

In [8543]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [8544]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [8545]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [8546]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [8547]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [8548]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [8549]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [8551]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

           TEST_8
R0030         0.0
R0040       614.0
R0050         0.0
R0060       768.0
R0070   5155576.0
R0220   4735704.0
R0230         0.0
R0270      8448.0
R0350         0.0
R0360      3402.0
R0370      1878.0
R0380    190609.0
R0390         0.0
R0400         0.0
R0410     82134.0
R0420       848.0
R0500  10179979.0

In [8552]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [8553]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [8554]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [8555]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [8556]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [8557]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [8558]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [8559]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [8560]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## AXA MPS Assicurazioni Vita

In [8561]:
unique_code = "AXA"

In [8562]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [8563]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [8564]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [8565]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [8566]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [8567]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [8568]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [8569]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [8570]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [8571]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [8572]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [8573]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [8574]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [8575]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [8576]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [8577]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [8578]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## CRÈDIT AGRICOLE VITA

In [8579]:
unique_code = "CREDIT_AGRICOLE"

In [8580]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [8581]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [8582]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [8583]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [8584]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [8585]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [8586]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [8587]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [8588]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [8589]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [8590]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [8591]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [8592]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [8593]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [8594]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [8595]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [8596]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## Società Reale Mutua di Assicurazioni

In [8597]:
unique_code = "REALE_MUTUA"

In [8598]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [8599]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [8600]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [8601]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [8602]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [8603]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [8604]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [8605]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [8606]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [8607]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [8608]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [8609]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [8610]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [8611]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [8612]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [8613]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [8614]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## Cardif Vita S.p.A.

In [8615]:
unique_code = "CARDIF"

In [8616]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [8617]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [8618]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [8619]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [8620]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [8621]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [8622]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [8623]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [8624]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [8625]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [8626]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [8627]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [8628]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [8629]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [8630]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [8631]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [8632]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## MEDIOLANUM VITA S.p.A.

In [8633]:
unique_code = "MEDIOLANUM"

In [8634]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [8635]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [8636]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [8637]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [8638]:
dirty_table_ita.loc["R0280", unique_code] = -1 * dirty_table_ita.loc["R0280", unique_code]

In [8639]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [8640]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [8641]:
dirty_table_ita.loc["R0290", unique_code] = -1 * dirty_table_ita.loc["R0290", unique_code]
dirty_table_ita.loc["R0300", unique_code] = -1 * dirty_table_ita.loc["R0300", unique_code]

In [8642]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [8643]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [8644]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [8645]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [8646]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [8647]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [8648]:
dirty_table_ita.loc["R0630", unique_code] = -1 * dirty_table_ita.loc["R0630", unique_code]

In [8649]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [8650]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [8651]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [8652]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [8653]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## Generali Italia S.p.A.

In [8654]:
unique_code = "GENERALI_ITALIA"

In [8655]:
dirty_table_ita.loc["R0100", unique_code] = 4034485

In [8656]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [8657]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [8658]:
dirty_table_ita.loc["R0100", unique_code] = 4034485

In [8659]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [8660]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [8661]:
dirty_table_ita.loc["R0270", unique_code] = 3446430

In [8662]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [8663]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [8664]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [8665]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [8666]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [8667]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [8668]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [8669]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [8670]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [8671]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [8672]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [8673]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [8674]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## Banco BPM Vita S.p.A.

In [8675]:
unique_code = "BMP_VITA"

In [8676]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [8677]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [8678]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [8679]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [8680]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [8681]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [8682]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [8683]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [8684]:
dirty_table_ita.loc["R0510",unique_code] = 1410

In [8685]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [8686]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [8687]:
dirty_table_ita.loc["R0590",unique_code] = 7

In [8688]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [8689]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [8690]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [8691]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [8692]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [8693]:
dirty_table_ita.loc["R0860",unique_code] = 0

In [8694]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [8695]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## HDI ASSICURAZIONI S.p.A.

In [8696]:
unique_code = "HDI"

In [8697]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [8698]:
dirty_table_ita.loc["R0130", unique_code] = 5016257

In [8699]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [8700]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [8701]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [8702]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [8703]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [8704]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [8705]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [8706]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [8707]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [8708]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [8709]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [8710]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [8711]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [8712]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [8713]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [8714]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## Gruppo Assicurativo Poste Vita

In [8715]:
unique_code = "POSTE_VITA"

In [8716]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [8717]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [8718]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [8719]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [8720]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [8721]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [8722]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [8723]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

            TEST_8
R0030          0.0
R0040    1659986.0
R0050          0.0
R0060      25718.0
R0070  145553398.0
R0220   16973297.0
R0230        320.0
R0270     280157.0
R0350          1.0
R0360     227971.0
R0370       6468.0
R0380       8346.0
R0390          0.0
R0400          0.0
R0410    4690070.0
R0420    2355396.0
R0500  171781131.0

In [8724]:
dirty_table_ita.loc["R0520", unique_code] = 236789
dirty_table_ita.loc["R0560", unique_code] = 383452
dirty_table_ita.loc["R0510", unique_code] = 620241

In [8725]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [8726]:
dirty_table_ita.loc["R0530", unique_code] = 0
dirty_table_ita.loc["R0540", unique_code] = 228156
dirty_table_ita.loc["R0550", unique_code] = 8633

In [8727]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [8728]:
dirty_table_ita.loc["R0570", unique_code] = 0
dirty_table_ita.loc["R0580", unique_code] = 361817
dirty_table_ita.loc["R0590", unique_code] = 21635

In [8729]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [8730]:
dirty_table_ita.loc["R0600", unique_code] = 135431267

In [8731]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [8732]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [8733]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [8734]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [8735]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [8736]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## FIDEURAM VITA S.P.A.

In [8737]:
unique_code = "INTESA_VITA"

In [8738]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [8739]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [8740]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [8741]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [8742]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [8743]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [8744]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [8745]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [8746]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [8747]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [8748]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [8749]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [8750]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [8751]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [8752]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [8753]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [8754]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## CNP Vita Assicura S.p.A.

In [8755]:
unique_code = "CNP_VITA"

In [8756]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [8757]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [8758]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [8759]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [8760]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [8761]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [8762]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [8763]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

           TEST_8
R0030         0.0
R0040         0.0
R0050         0.0
R0060      3242.0
R0070  18123968.0
R0220   6779537.0
R0230       757.0
R0270     31280.0
R0350         0.0
R0360      6516.0
R0370     16098.0
R0380    399567.0
R0390         0.0
R0400         0.0
R0410    340483.0
R0420     60719.0
R0500  25762169.0

In [8764]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [8765]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [8766]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [8767]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [8768]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [8769]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [8770]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [8771]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [8772]:
dirty_table_ita.loc["R0900", unique_code] = 23999137

In [8773]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

# ITAS VITA

In [8774]:
unique_code = "ITAS_VITA"

In [8775]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [8776]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [8777]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [8778]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [8779]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [8780]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [8781]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [8782]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [8783]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [8784]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [8785]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [8786]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [8787]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [8788]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [8789]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [8790]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [8791]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## Helvetia Vita S.p.A.

In [8792]:
unique_code = "HELVATIA_VITA"

In [8793]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [8794]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [8795]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [8796]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [8797]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [8798]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [8799]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [8800]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [8801]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [8802]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [8803]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [8804]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [8805]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [8806]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [8807]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [8808]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [8809]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## Vittoria Assicurazioni S.p.A.

In [8810]:
unique_code = "VITTORIA"

In [8811]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [8812]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [8813]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [8814]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [8815]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [8816]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [8817]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [8818]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [8819]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [8820]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [8821]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [8822]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [8823]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [8824]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [8825]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [8826]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [8827]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## GROUPAMA ASSICURAZIONI S.P.A.

In [8828]:
unique_code = "GROUPAMA"

In [8829]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [8830]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [8831]:
dirty_table_ita.loc["R0070", unique_code] = 3780211

In [8832]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [8833]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [8834]:
dirty_table_ita.loc["R0310", unique_code] = 2458
dirty_table_ita.loc["R0280", unique_code] = 78988

In [8835]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [8836]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [8837]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [8838]:
dirty_table_ita.loc["R0380", unique_code] = 159382
dirty_table_ita.loc["R0420", unique_code] = 151684

In [8839]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [8840]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [8841]:
dirty_table_ita.loc["R0550", unique_code] = 57467

In [8842]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [8843]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [8844]:
dirty_table_ita.loc["R0650", unique_code] = 1749477

In [8845]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [8846]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [8847]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [8848]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [8849]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [8850]:
dirty_table_ita.loc["R0900",unique_code] = 4518565
dirty_table_ita.loc["R1000",unique_code] = 809509

In [8851]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## UniCredit Allianz Vita S.p.A.

In [8852]:
unique_code = "ALLIANZ_UNICREDIT"

In [8853]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [8854]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [8855]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [8856]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [8857]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [8858]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [8859]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [8860]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [8861]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [8862]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [8863]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [8864]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [8865]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [8866]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [8867]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [8868]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [8869]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## Zurich Investments Life S.p.A.

In [8870]:
unique_code = "ZURICH_LIFE"

In [8871]:
result,diagnostics, diff = check_02_01_02_1(dirty_table_ita, eps, unique_code)
diagnostics

In [8872]:
result,diagnostics, diff = check_02_01_02_2(dirty_table_ita, eps, unique_code)
diagnostics

In [8873]:
result,diagnostics, diff = check_02_01_02_3(dirty_table_ita, eps, unique_code)
diagnostics

In [8874]:
result,diagnostics, diff = check_02_01_02_4(dirty_table_ita, eps, unique_code)
diagnostics

In [8875]:
result,diagnostics, diff = check_02_01_02_5(dirty_table_ita, eps, unique_code)
diagnostics

In [8876]:
result,diagnostics, diff = check_02_01_02_6(dirty_table_ita, eps, unique_code)
diagnostics

In [8877]:
result,diagnostics, diff = check_02_01_02_7(dirty_table_ita, eps, unique_code)
diagnostics

In [8878]:
result,diagnostics, diff = check_02_01_02_8(dirty_table_ita, eps, unique_code)
diagnostics

In [8879]:
dirty_table_ita.loc["R0600",unique_code] = 4440687
dirty_table_ita.loc["R0650",unique_code] = 4440687
dirty_table_ita.loc["R0670",unique_code] = 4368246
dirty_table_ita.loc["R0680",unique_code] = 72441
dirty_table_ita.loc["R0690",unique_code] = 5577792
dirty_table_ita.loc["R0710",unique_code] = 5530993
dirty_table_ita.loc["R0720",unique_code] = 46798
dirty_table_ita.loc["R0750",unique_code] = 51247
dirty_table_ita.loc["R0760",unique_code] = 1122
dirty_table_ita.loc["R0770",unique_code] = 25231
dirty_table_ita.loc["R0780",unique_code] = 89540
dirty_table_ita.loc["R0810",unique_code] = 3744
dirty_table_ita.loc["R0820",unique_code] = 37135
dirty_table_ita.loc["R0830",unique_code] = 3101
dirty_table_ita.loc["R0840",unique_code] = 19918
dirty_table_ita.loc["R0880",unique_code] = 30708
dirty_table_ita.loc["R0900",unique_code] = 10280225
dirty_table_ita.loc["R1000",unique_code] = 696507

In [8880]:
result,diagnostics, diff = check_02_01_02_9(dirty_table_ita, eps, unique_code)
diagnostics

In [8881]:
result,diagnostics, diff = check_02_01_02_10(dirty_table_ita, eps, unique_code)
diagnostics

In [8882]:
result,diagnostics, diff = check_02_01_02_11(dirty_table_ita, eps, unique_code)
diagnostics

In [8883]:
result,diagnostics, diff = check_02_01_02_12(dirty_table_ita, eps, unique_code)
diagnostics

In [8884]:
result,diagnostics, diff = check_02_01_02_13(dirty_table_ita, eps, unique_code)
diagnostics

In [8885]:
result,diagnostics, diff = check_02_01_02_14(dirty_table_ita, eps, unique_code)
diagnostics

In [8886]:
result,diagnostics, diff = check_02_01_02_15(dirty_table_ita, eps, unique_code)
diagnostics

In [8887]:
result,diagnostics, diff = check_02_01_02_16(dirty_table_ita, eps, unique_code)
diagnostics

In [8888]:
result,diagnostics, diff = check_02_01_02_17(dirty_table_ita, eps, unique_code)
diagnostics

## Master table after cross checks

In [8889]:
dirty_table_ita.to_csv("Cleaner_Combined/Table_ita_S02.csv")